/*
SET NOEXEC OFF;
--*/ SET NOEXEC ON;
GO

USE master;
GO

EXEC msdb.dbo.sp_delete_database_backuphistory @database_name = N'DWFHP'
GO

ALTER DATABASE [DWFHP] SET  SINGLE_USER WITH ROLLBACK IMMEDIATE
GO

DROP DATABASE [DWFHP]
GO

CREATE DATABASE [DWFHP]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DWFHP', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQL2017\MSSQL\DATA\DWFHP.mdf' , SIZE = 65536KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DWFHP_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQL2017\MSSQL\DATA\DWFHP_log.ldf' , SIZE = 65536KB , FILEGROWTH = 65536KB )
COLLATE Latin1_General_CI_AS;
GO
ALTER DATABASE [DWFHP] SET COMPATIBILITY_LEVEL = 140
GO
ALTER DATABASE [DWFHP] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [DWFHP] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [DWFHP] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [DWFHP] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [DWFHP] SET ARITHABORT OFF 
GO
ALTER DATABASE [DWFHP] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [DWFHP] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DWFHP] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [DWFHP] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DWFHP] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DWFHP] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DWFHP] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [DWFHP] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DWFHP] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [DWFHP] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DWFHP] SET  DISABLE_BROKER 
GO
ALTER DATABASE [DWFHP] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DWFHP] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DWFHP] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DWFHP] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [DWFHP] SET  READ_WRITE 
GO
ALTER DATABASE [DWFHP] SET RECOVERY FULL 
GO
ALTER DATABASE [DWFHP] SET  MULTI_USER 
GO
ALTER DATABASE [DWFHP] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [DWFHP] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [DWFHP] SET DELAYED_DURABILITY = DISABLED 
GO

USE [DWFHP]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = On;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = Primary;
GO

USE [DWFHP]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [DWFHP] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
